[package]
name = "cottas-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
duckdb = { version = "1.4.2", features = ["bundled"] }
oxrdf = "0.3.1"
oxrdfio = "0.2.1"
polars = { version = "0.52", features = ["parquet"] }